"""user data tables

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-07-18 00:43:56.056809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8c9d0e1f2a3'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('above','below')", name='ck_alert_direction'),
    sa.CheckConstraint('price > 0 AND price <= 1000000000000', name='ck_alert_price'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_key', 'direction', 'price', name='uq_user_alerts')
    )
    op.create_index('ix_user_alerts_user', 'user_alerts', ['user_id'], unique=False)
    op.create_table('user_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_key', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_cost IS NULL OR (avg_cost >= 0 AND avg_cost <= 1000000000000)', name='ck_holding_cost'),
    sa.CheckConstraint('qty > 0 AND qty <= 1000000000000', name='ck_holding_qty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_key', name='uq_user_holdings')
    )
    op.create_index('ix_user_holdings_user', 'user_holdings', ['user_id'], unique=False)
    op.create_table('user_prefs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lang', sa.String(length=5), server_default='az', nullable=False),
    sa.Column('theme', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_saved_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_key', name='uq_user_saved_events')
    )
    op.create_index('ix_user_saved_events_user', 'user_saved_events', ['user_id', sa.literal_column('saved_at DESC')], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_key', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_key', name='uq_user_watchlist')
    )
    op.create_index('ix_user_watchlist_user', 'user_watchlist', ['user_id', 'created_at'], unique=False)
    op.create_table('user_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='uq_user_bookmarks')
    )
    op.create_index('ix_user_bookmarks_user', 'user_bookmarks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_bookmarks_user', table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    op.drop_index('ix_user_watchlist_user', table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index('ix_user_saved_events_user', table_name='user_saved_events')
    op.drop_table('user_saved_events')
    op.drop_table('user_prefs')
    op.drop_index('ix_user_holdings_user', table_name='user_holdings')
    op.drop_table('user_holdings')
    op.drop_index('ix_user_alerts_user', table_name='user_alerts')
    op.drop_table('user_alerts')
    # ### end Alembic commands ###
